services:
  devcontainer:
    image: ${DEVCONTAINER}
    command: sleep infinity
    environment:
      PGHOST: ${POSTGRES_HOST}
      PGUSER: postgres
      PGPASSWORD: ${DB_PASSWORD}
    volumes:
      - ..:/var/www/rnd:cached
      - home:/home
      - root:/root

  redis:
    image: redis:alpine
    network_mode: service:devcontainer
    restart: unless-stopped
    volumes:
      - type: volume
        source: redis_data
        target: /data;

  postgresdb:
    restart: unless-stopped
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
    - published: 55432
      target: 5432
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
