name: 'Create Branch'
inputs:
  branch-name:
    type: string
    required: true
  sha:
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      with:
        script: |
          try {
            const branch_rsp = await github.rest.git.createRef({
              ...context.repo,
              ref: 'refs/heads/${{ inputs.branch-name }}',
              sha: '${{ inputs.sha }}'
            });
            if (branch_rsp.status !== 409) {
              core.setFailed(`Failed to create branch object (status=${branch_rsp.status})`);
              return;
            }

            const update_branch_rsp = await github.rest.git.updateRef({
              ...context.repo,
              ref: 'refs/heads/${{ inputs.branch-name }}',
              sha: '${{ inputs.sha }}',
              force: true
            });

            if (update_branch_rsp.status !== 200) {
              core.setFailed(`Failed to update branch object (status=${update_branch_rsp.status})`);
            }
          } catch (error) {
            core.setFailed(error.message);
          }



