name: 'Create Branch'
inputs:
  owner:
    type: string
    required: true
  repo:
    type: string
    required: true
  branch-name:
    type: string
    required: true
  sha:
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      with:
        script: |
          try {
            await github.rest.git.createRef({
              owner: '${{inputs.owner }}',
              repo:'${{ inputs.repo }}',
              ref: 'refs/heads/${{ inputs.branch-name }}',
              sha: '${{ inputs.sha }}'
            });
          } catch (e) {
            await github.rest.git.updateRef({
              owner: '${{inputs.owner }}',
              repo: '${{ inputs.repo }}',
              ref: 'refs/heads/${{ inputs.branch-name }}',
              sha: '${{ inputs.sha }}',
              force: true
            });
          }



