mode: auto
branchName: tiny
silent: false
autoLinkIssue: true
autoCloseIssue: false
autoDeleteBranch: false

openDraftPR: true

conventionalPrTitles: true
conventionalStyle: semver

copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: false

branches:
  - label:
      - enhancement
      - 'status: confirmed'
    prefix: feat/
  - label:
      - bug
      - 'status: confirmed'
    prefix: fix/
  - label:
      - chore
      - 'status: confirmed'
    prefix: chore/
  - label:
      - documentation
      - 'status: confirmed'
    prefix: docs/
  - label: '*'
    skip: true
