mode: auto
branchName: short
silent: false
autoLinkIssue: true
autoCloseIssue: true
autoDeleteBranch: true
openDraftPR: true

conventionalPrTitles: true
conventionalStyle: semver

copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true

branches:
  - label: enhancement
    prefix: feat/
  - label: bug
    prefix: fix/
  - label: chore
    prefix: chore/
  - label: documentation
    prefix: docs/
  - label: '*'
    skip: true
