mode: auto
branchName: short
silent: true
autoDeleteBranch: true
branches:
  - label: enhancement
    prefix: feat/
  - label: bug
    prefix: fix/
  - label: chore
    prefix: chore/
  - label: documentation
    prefix: docs/
  - label: '*'
    prefix: issue/
