mode: auto
branchName: short
silent: true
autoCloseIssue: true
autoDeleteBranch: true
openDraftPR: true
prSkipCI: true
conventionalPrTitles: true
branches:
  - label: enhancement
    prefix: feat/
  - label: bug
    prefix: fix/
  - label: chore
    prefix: chore/
  - label: documentation
    prefix: docs/
  - label: '*'
    skip: true
