name: 'Create Tag'
inputs:
  owner:
    type: string
    required: true
  repo:
    type: string
    required: true
  tag-name:
    type: string
    required: true
  sha:
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      with:
        script: |
          try {
            await github.rest.git.deleteRef({
              owner: '${{inputs.owner }}',
              repo: '${{ inputs.repo }}',
              ref: 'refs/tags/${{ inputs.tag-name }}'
            });
          } catch (e) {}
          await github.rest.git.createTag({
            owner: '${{inputs.owner }}',
            repo: '${{ inputs.repo }}',
            tag: '${{ inputs.tag-name }}',
            message: 'Release ${{ inputs.tag-name }}',
            type: 'commit',
            object: '${{ inputs.sha }}'
          });
          await github.rest.git.createRef({
            owner: '${{inputs.owner }}',
            repo: '${{ inputs.repo }}',
            ref: 'refs/tags/${{ inputs.tag-name }}',
            sha: '${{ inputs.sha }}'
          });



