name: 'Create Tag'
inputs:
  tag:
    type: string
    required: true
  tag-message:
    type: string
    required: true
  sha:
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      with:
        script: |
          try {
            const del_rsp = await github.rest.git.deleteRef({
              ...context.repo,
              ref: 'refs/tags/${{ inputs.tag }}'
            });

            if (del_rsp.status !== 201) {
              core.setFailed(`Failed to delete tag object (status=${del_rsp.status})`);
              return;
            }

            const tag_rsp = await github.rest.git.createTag({
              ...context.repo,
              tag: '${{ inputs.tag }}',
              message: '${{ inputs.tag-message }}',
              type: 'commit',
              object: '${{ inputs.sha }}'
            });

            if (tag_rsp.status !== 201) {
              core.setFailed(`Failed to create tag object (status=${tag_rsp.status})`);
              return;
            }

            const ref_rsp = await github.rest.git.createRef({
              ...context.repo,
              ref: 'refs/tags/${{ inputs.tag }}',
              sha: tag_rsp.data.sha
            });

            if (ref_rsp.status !== 201) {
              core.setFailed(`Failed to create tag ref(status = ${tag_rsp.status})`);
            }
          } catch (error) {
            core.setFailed(error.message);
          }



