services:
  devcontainer:
    image: ghcr.io/bagermen/rnd-images/devcontainer:1.4.0
    command: sleep infinity
    ports:
    - published: 55432
      target: 5432
    - published: 56379
      target: 6379
    volumes:
      - ..:/etc/bpmsoft:cached
      - home:/home
  postgresdb:
    network_mode: service:devcontainer
    restart: unless-stopped
    # image: postgres:16.4-alpine
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: 123
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data

  redis:
    image: redis:alpine
    network_mode: service:devcontainer
    restart: unless-stopped
    volumes:
      - type: volume
        source: redis_data
        target: /data
volumes:
  home:
  redis_data:
    external: true
    name: redis_bpmsoft
  postgres_data:
    external: true
    name: postgres_bpmsoft
