name: 'Image Variants'
outputs:
  matrix: ${{ steps.generate.outputs.matrix }}
runs:
  using: composite
  steps:
    - id: generate
      uses: mmastrac/mmm-matrix@v1
        with:
          input: |
            default:
              os: debian
              file: Dockerfile
              variant:
            ubuntu:
              os: ubuntu
              file: Dockerfile
              variant: -noble



