name: 'Image Variants'
outputs:
  matrix:
    value: ${{ steps.generate.outputs.matrix }}
runs:
  using: 'composite'
  steps:
    - id: generate
      uses: mmastrac/mmm-matrix@v1
      with:
        input: |
          $array:
            - os: debian
              variant: ''
            - os: ubuntu
              variant: -noble
              file: Dockerfile1
          file: Dockerfile



