on:
  workflow_call:
    inputs:
      ref:
        description: The branch, tag or SHA to checkout
        required: true
        type: string
      environment:
        description: Environment to build images against
        type: string
        required: true
      push:
        description: Push images
        type: boolean
        required: false
        default: true
    outputs:
      imageid:
        description: Image ID
        value: ${{ jobs.build_image.outputs.imageid }}
      digest:
        description: Image digest
        value: ${{ jobs.build_image.outputs.digest }}

permissions:
  packages: write
  contents: read
  id-token: write
  attestations: write

concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

env:
  IMAGE_NAME: rnd
  GH_REGISTRY: ghcr.io/${{ github.actor }}

jobs:
  build_image:
    name: Build base image
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      imageid: ${{ steps.build.outputs.imageid }}
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the current tag from the branch
        id: current-tag
        run: |
          echo "VALUE=$(git describe --tags --candidates=0 2>/dev/null)" >> "$GITHUB_OUTPUT"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=false
          labels: |
            org.opencontainers.image.title=rnd
            org.opencontainers.image.description=base rnd image
          images: |
            ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # releases
            type=semver,priority=900,pattern={{version}},value=${{ steps.current-tag.outputs.VALUE }}
            # edge
            type=edge,priority=700
            # branch
            type=ref,priority=600,event=branch

      - name: Throw error if tags have not been generated
        if: ${{ steps.meta.outputs.tags == '' }}
        run: |
            echo "::error::Tags were not set"
            exit 1

      - name: Build and optionally push image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: base/Dockerfile
          push: ${{ vars.ACTIONS_STEP_DEBUG != 'true' && inputs.push == 'true' }}
          sbom: ${{ vars.ACTIONS_STEP_DEBUG != 'true' && inputs.push == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          build-args: |
            cache-from: type=gha
            cache-to: type=gha,mode=max

      - name: Generate artifact attestation (GitHub)
        if: ${{ vars.ACTIONS_STEP_DEBUG != 'true' && inputs.push == 'true' }}
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build.outputs.digest }}
          github-token: ${{ github.token }}
          push-to-registry: true
