name: ci / release

on:
  release:
    types: [published]

permissions:
  packages: write
  contents: read
  id-token: write
  attestations: write

jobs:
  build_images:
    uses: ./.github/workflows/_wc_build_base_image.yml
    secrets: inherit
    with:
      ref: ${{ github.event.release.tag_name  }}
      environment: development
