name: ci / push templates

on:
  push:
    branches:
      - '*/issue-*'
    paths:
      - 'templates/**'

env:
  ROOT_PATH: templates

jobs:
  regenerate_documentation:
    runs-on: ubuntu-latest
    environment: development

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
              .github
              ${{ env.ROOT_PATH }}

      - name: Generate template documentation
        uses: devcontainers/action@v1
        with:
          generate-docs: 'true'
          base-path-to-templates: ${{ env.ROOT_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add documentation into git
        run: |
          git add ${{ env.ROOT_PATH }}/*/README.md

      - uses: qoomon/actions--create-commit@v1
        id: commit
        with:
          message: 'feat: generate templates README.md'
          skip-empty: true

      - if: ${{ success() && steps.commit.outputs.commit }}
        run: git push
