name: ci / pr check
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

permissions:
  packages: write
  contents: read
  id-token: write
  attestations: write

jobs:
  test_changed_project:
    if: ${{ github.event.pull_request.draft == false &&  !contains(github.event.pull_request.labels.*.name, 'autorelease') }}
    runs-on: ubuntu-latest
    name: Test changed files
    outputs:
      base: ${{ steps.base.outputs.any_modified }}
    steps:
      - uses: actions/checkout@v4
      - id: base
        uses: tj-actions/changed-files@v45
        with:
          since_last_remote_commit: true
          path: base
          files_ignore: |
            - **.md
            - docs/**

  test_base_image:
    needs: [test_changed_project]
    if: ${{ !cancelled() && !failure() && needs.test_changed_project.outputs.base == 'true' }}
    uses: ./.github/workflows/_wc_build_base_image.yml
    secrets: inherit
    with:
      ref: ${{ github.ref }}
      environment: development
      push: false

