name: ci / release

on:
  push:
    branches:
      - main
jobs:
  release_please:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      pull-requests: write

    outputs:
      releases_created: ${{ steps.release_please.outputs.releases_created }}
      base_released: ${{ steps.release_please.outputs.base--release_created }}
      base_tag_name: ${{ steps.release_please.outputs.base--tag_name }}
      base_major_released: ${{ steps.release_please.outputs.releases_created && steps.release_please.outputs.base--major > steps.current_base_release.outputs.major }}
      devcontainer_released: ${{ steps.release_please.outputs.devcontainer--release_created }}
      devcontainer_tag_name: ${{ steps.release_please.outputs.devcontainer--tag_name }}
      rnd-compose_released: ${{ steps.release_please.outputs.rnd-compose--release_created }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github

      - name: read current releases
        id: current_releases
        uses: ActionsTools/read-json-action@v1.0.5
        with:
          file_path: .github/.release-manifest.json

      - name: parse versions from base release
        id: current_base_release
        uses: release-kit/semver@v2
        with:
          string: ${{ steps.current_releases.outputs.base }}

      - uses: googleapis/release-please-action@v4
        id: release_please
        with:
          token: ${{ secrets.PAT }}
          config-file: .github/release-config.json
          manifest-file: .github/.release-manifest.json
          include-component-in-tag: true

      - uses: ./.github/actions/create-release-refs
        if: ${{ steps.release_please.outputs.base--release_created == 'true' }}
        with:
          component: base
          major: ${{ steps.release_please.outputs.base--major }}
          minor: ${{ steps.release_please.outputs.base--minor }}

      - uses: ./.github/actions/create-release-refs
        if: ${{ steps.release_please.outputs.devcontainer--release_created == 'true' }}
        with:
          component: devcontainer
          major: ${{ steps.release_please.outputs.devcontainer--major }}
          minor: ${{ steps.release_please.outputs.devcontainer--minor }}

      - uses: ./.github/actions/create-release-refs
        if: ${{ steps.release_please.outputs.devcontainer--release_created == 'true' }}
        with:
          component: devcontainer
          major: ${{ steps.release_please.outputs.devcontainer--major }}
          minor: ${{ steps.release_please.outputs.devcontainer--minor }}

  publish_base_image:
    uses: ./.github/workflows/_wc_build_base_image.yml
    needs: [release_please]
    if: ${{ !cancelled() && !failure() && needs.release_please.outputs.base_released == 'true' }}

    permissions:
      packages: write
      contents: read
      id-token: write
      attestations: write

    secrets: inherit
    with:
      ref: ${{ needs.release_please.outputs.base_tag_name }}
      environment: production
      push: true

  publish_devcontainer_image:
    uses: ./.github/workflows/_wc_build_devcontainer.yml
    needs: [release_please, publish_base_image]
    if: ${{ !cancelled() && !failure() && (needs.release_please.outputs.devcontainer_released == 'true' || needs.release_please.outputs.base_major_released == 'true') }}

    permissions:
      packages: write
      contents: read

    secrets: inherit
    with:
      ref: ${{ needs.release_please.outputs.devcontainer_tag_name }}
      environment: production
      push: true

  publish_templates:
    uses: ./.github/workflows/_wc_build_templates.yml
    needs: [release_please]
    if: ${{ !cancelled() && !failure() && (needs.release_please.outputs.rnd-compose_released == 'true') }}

    permissions:
      packages: write
      contents: read
    secrets: inherit
    with:
      ref: ${{ github.ref }}
      environment: production
      push: true

  label_release:
    runs-on: ubuntu-latest
    environment: production
    needs: [release_please, publish_base_image, publish_devcontainer_image]
    if: ${{ !cancelled() && !failure() && needs.release_please.outputs.releases_created == 'true' }}

    permissions:
      pull-requests: write
      contents: read

    steps:
      - uses: cloudposse-github-actions/get-pr@v2
        id: pr
      - uses: PauMAVA/add-remove-label-action@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          issue_number: ${{ steps.pr.outputs.number }}
          add: 'autorelease: published'
