name: ci / pr check
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
jobs:
  list_projects:
    if: ${{ github.event.pull_request.draft == false && !contains(join(github.event.pull_request.labels.*.name), 'autorelease') }}
    runs-on: ubuntu-latest
    environment: development
    outputs:
      matrix: ${{ steps.project-list.outputs.matrix }}
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          useGlob: true
          name: |
            *.json
      - uses: mmastrac/mmm-matrix@v1
        id: project-list
        with:
          input: |
            - artifact: base.json
              path: base
              src_files: |
                !**.md
                !docs/**
  check_changes:
    needs: [list_projects]
    if: ${{ !cancelled() && !failure() }}
    strategy:
      matrix:
        include: ${{ fromJSON(needs.list_projects.outputs.matrix) }}
    uses: ./.github/workflows/_wc_test_pr_changes.yml
    with:
      environment: development
      artifact: ${{ matrix.artifact }}
      path: ${{ matrix.path }}
      src_files: ${{ matrix.src_files }}

  read_changes:
    if: ${{ !cancelled() && !failure() }}
    needs: [list_projects, check_changes]
    runs-on: ubuntu-latest
    environment: development
    outputs:
      path: ${{ steps.project.outputs.value }}
      src_modified: ${{ fromJson(steps.artifact.outputs.content).src_modified }}
      test_modified: ${{ fromJson(steps.artifact.outputs.content).test_modified }}
    strategy:
      matrix:
        include: ${{ fromJSON(needs.list_projects.outputs.matrix) }}
    steps:
      - uses: streetsidesoftware/action-set-output@v1
        id: project
        with:
          value: ${{ matrix.path }}
      - uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.artifact }}
      - id: artifact
        uses: juliangruber/read-file-action@v1
        with:
          path: ${{ matrix.artifact }}

  test_base_image:
    needs: [read_changes]
    if: ${{ !cancelled() && !failure() && needs.read_changes.outputs.path == 'base' && needs.read_changes.outputs.src_modified == 'true' }}
    uses: ./.github/workflows/_wc_build_base_image.yml
    permissions:
      packages: write
      contents: read
      id-token: write
      attestations: write
    secrets: inherit
    with:
      ref: ${{ github.ref }}
      environment: development
      push: false

