name: ci / base check
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - base/**

permissions:
  packages: write
  contents: read
  id-token: write
  attestations: write

jobs:
  base_changed_files:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    name: Test changed-files
    outputs:
      any_modified: ${{ steps.changed-files.outputs.any_modified }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            base
      - name: Detect changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          path: base
          files_ignore: |
            *.md
            docs/**

  base_check:
    needs: [base_changed_files]
    if: ${{ needs.base_changed_files.outputs.any_modified == true }}
    uses: ./.github/workflows/_wc_build_base_image.yml
    secrets: inherit
    with:
      ref: ${{ github.ref }}
      environment: development
      push: false

