name: pm / issues

on:
  issues:
    types: [ assigned, labeled, unlabeled ]
  pull_request:
    types: [ opened, closed ]

permissions:
  contents: write
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Create Issue Branch
        id: create-issue-branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
