name: pm / release-please

on:
  push:
    branches:
      - main
jobs:
  release_please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    outputs:
      result: ${{ steps.release_please.outputs }}

    steps:
      - uses: googleapis/release-please-action@v4
        id: release_please
        with:
          token: ${{ secrets.PAT }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  publish_base_image:
    if: ${{ !cancelled() && !failure() && needs.release_please.outputs.result.base--release_created }}
    needs: [release_please]

    permissions:
      packages: write
      contents: read
      id-token: write
      attestations: write

    uses: ./.github/workflows/_wc_build_base_image.yml
    secrets: inherit
    with:
      ref: ${{ needs.release_please.outputs.result.base--tag_name  }}
      environment: production
      push: true
