name: pm / issues

on:
  issues:
    types: [assigned]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'assigned' }}
    environment: development
    steps:
      - name: Create Issue Branch
        id: create-issue-branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Results
        env:
          BRANCH_NAME: ${{ steps.create-issue-branch.outputs.branchName }}
        run: |
          echo $BRANCH_NAME
          node -v
