on:
  workflow_call:
    inputs:
      ref:
        description: The branch, tag or SHA to checkout
        required: true
        type: string
      environment:
        description: Environment to build images against
        type: string
        required: true
      push:
        description: Push images
        type: boolean
        required: false
        default: true

permissions:
  packages: write
  contents: read

concurrency:
    group: ci-templates-${{ inputs.ref }}
    cancel-in-progress: true
env:
  ROOT_PATH: templates

jobs:
  build_image:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
            ref: ${{ inputs.ref }}
            sparse-checkout: |
              .github
              ${{ env.ROOT_PATH }}

      - id: variants
        uses: ./.github/actions/image-variants

      - name: Make compose file copy
        uses: actions/github-script@v7
        with:
          script: |
            const variants = JSON.parse('${{ steps.variants.outputs.matrix }}');
            const basePath = '${{ env.ROOT_PATH }}';
            const templatesGlobber = await glob.create(`${basePath}/*`);
            const templates = await templatesGlobber.glob();

            for (const template of templates) {
              core.info(template);
            }

      - name: Build and optionally push image
        uses: devcontainers/action@v1
        with:
          publish-templates: ${{ inputs.push && 'true' || 'false' }}
          oci-registry-for-templates: 'ghcr.io'
          templates-namespace: ${{ github.repository }}
          disable-repo-tagging: 'true'
          base-path-to-templates: ./${{ env.ROOT_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
