on:
  workflow_call:
    inputs:
      path:
        description: Project folder
        required: true
        type: string
      src_files:
        description: Source code files
        required: true
        type: string
      test_files:
        description: Test files
        type: string
      artifact:
        description: Artifact file
        type: string
      environment:
        description: Environment to build images against
        type: string
        default: production

    outputs:
      src_modified:
        value: ${{ jobs.test_changes.outputs.src_modified }}
      test_modified:
        value: ${{ jobs.test_changes.outputs.test_modified }}
env:
  PROJECT_CHECK_FAILED: '${{ inputs.path }} check fails'

jobs:
  test_changes:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    outputs:
      src_modified: ${{ steps.src-files.outputs.any_modified }}
      test_modified: ${{ steps.test-files.outputs.any_modified }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ inputs.path }}
      - id: all-files
        uses: tj-actions/changed-files@v45
        with:
          since_last_remote_commit: true
          path: ${{ inputs.path }}
      - id: src-files
        uses: tj-actions/changed-files@v45
        with:
          since_last_remote_commit: true
          path: ${{ inputs.path }}
          files: ${{ inputs.src_files }}

      - id: test-files
        if: ${{ inputs.test_files != '' }}
        uses: tj-actions/changed-files@v45
        with:
          since_last_remote_commit: true
          path: ${{ inputs.path }}
          files: ${{ inputs.test_files }}
      - id: last_ref_status
        if: ${{ steps.src-files.outputs.any_modified == 'false' && steps.all-files.outputs.any_modified == 'true' }}
        uses: danieldeichfuss/get-status@v0.0.10
        with:
            ref: ${{ github.event.pull_request.head.sha }}
      - if: ${{ inputs.test_files == '' && steps.src-files.outputs.any_modified == 'false' && steps.all-files.outputs.any_modified == 'true' && steps.last_ref_status.outputs.all-checks-passed == 'false' }}
        uses: actions/github-script@v7
        with:
          script:  core.setFailed('${{env.PROJECT_CHECK_FAILED}}')

      - if: ${{ inputs.test_files != '' && steps.src-files.outputs.any_modified == 'false' && steps.test-files.outputs.any_modified == 'false' && steps.all-files.outputs.any_modified == 'true' && steps.last_ref_status.outputs.all-checks-passed == 'false' }}
        uses: actions/github-script@v7
        with:
          script:  core.setFailed('${{env.PROJECT_CHECK_FAILED}}')
      - uses: jsdaniell/create-json@v1.2.3
        if: ${{ inputs.artifact != ''}}
        with:
          name: ${{ inputs.artifact }}
          json: >
            {\"src_modified\":${{ steps.src-files.outputs.any_modified }},\"test_modified\":${{ steps.test-files.outputs.any_modified == 'true' }}}
      - uses: actions/upload-artifact@v4
        if: ${{ inputs.artifact != ''}}
        with:
          name: ${{ inputs.artifact }}
          path: ${{ inputs.artifact }}
