on:
  workflow_call:
    inputs:
      ref:
        description: The branch, tag or SHA to checkout
        required: true
        type: string
      environment:
        description: Environment to build images against
        type: string
        required: true
      push:
        description: Push images
        type: boolean
        required: false
        default: true

concurrency:
    group: ci-templates-${{ github.ref }}
    cancel-in-progress: true
env:
  ROOT_PATH: templates

jobs:
  build_image:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
            ref: ${{ inputs.ref }}
            sparse-checkout: ${{ env.ROOT_PATH }}

      - name: Build and optionally push image
        uses: devcontainers/action@v1
        with:
          publish-templates: ${{ inputs.push && 'true' || 'false' }}
          oci-registry-for-templates: 'ghcr.io'
          templates-namespace: ${{ github.actor }}
          disable-repo-tagging: 'true'
          base-path-to-templates: ./${{ env.ROOT_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
