name: wd / build images

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The branch, tag or SHA to checkout
        required: true
        default: main
      environment:
        description: Environment
        type: environment
        required: true
      push:
        description: Push to registry
        type: boolean
        default: false
      target:
        description: Build target
        required: true
        type: choice
        default: 'base'
        options:
          - all
          - base
          - devcontainer
          - templates

permissions:
  packages: write
  contents: read
  id-token: write
  attestations: write

jobs:
  initiate:
    runs-on: ubuntu-latest
    outputs:
      image_variants: ${{ steps.variants.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github

      - id: variants
        uses: ./.github/actions/image-variants

  build_base_image:
    needs: [initiate]
    if: ${{ inputs.target == 'all' || inputs.target == 'base' }}
    strategy:
      matrix:
        include: ${{ fromJSON(needs.initiate.outputs.image_variants) }}

    secrets: inherit
    uses: ./.github/workflows/_wc_build_base_image.yml
    with:
      ref: ${{ inputs.ref }}
      environment: ${{ inputs.environment }}
      dockerfile: ${{ matrix.file }}
      suffix: ${{ matrix.variant }}
      push: ${{ inputs.push }}

  build_devcontainer_image:
    needs: [build_base_image, initiate]
    if: ${{ !cancelled() && !failure() && (inputs.target == 'all' || inputs.target == 'devcontainer') }}
    strategy:
      matrix:
        include: ${{ fromJSON(needs.initiate.outputs.image_variants) }}

    secrets: inherit
    uses: ./.github/workflows/_wc_build_devcontainer.yml
    with:
      ref: ${{ inputs.ref }}
      environment: ${{ inputs.environment }}
      suffix: ${{ matrix.variant }}
      push: ${{ inputs.push }}

  build_templates:
    if: ${{ !cancelled() && !failure() && (inputs.target == 'all' || inputs.target == 'templates') }}
    needs: [build_devcontainer_image]
    uses: ./.github/workflows/_wc_build_templates.yml
    secrets: inherit
    with:
      ref: ${{ inputs.ref }}
      environment: ${{ inputs.environment }}
      push: ${{ inputs.push }}


