name: wd / build images

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The branch, tag or SHA to checkout
        required: true
        default: main
      environment:
        description: Environment
        type: environment
        required: true
      push:
        description: Push to registry
        type: boolean
        default: false

permissions:
  packages: write
  contents: read
  id-token: write
  attestations: write

jobs:
  build_images:
    uses: ./.github/workflows/_wc_build_base_image.yml
    secrets: inherit
    with:
      ref: ${{ inputs.ref }}
      environment: ${{ inputs.environment }}
      push: ${{ inputs.push }}


